announcement bar created
marmetodevelopers/mivi-website pull request #2
Opened 2023-10-11 10:08 UTC by NikhitaDesai

### Problem
Created announcement bar and header as per the figma.
Monday Card Link :(announcement bar) https://marmeto-force.monday.com/boards/5104690360/pulses/5296291094
Monday Card Link ( header):https://marmeto-force.monday.com/boards/5104690360/pulses/5296291547
Preview link: https://mivi-website.myshopify.com/?preview_theme_id=161424736533
### Solution
Added the relatable CSS properties to match the given figma
![image](https://github.com/marmetodevelopers/mivi-website/assets/145182249/f463f81e-28c6-44c9-8549-4e8a0585d5a4)
### Impacted Areas
All pages
### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.
Please review this PR and provide feedback. Thank you!

2023-10-11 10:09 UTC, NikhitaDesai commented
@MadhanSamiappan Updated the changes, review the code

2023-10-11 10:50 UTC, MadhanSamiappan requested changes
refer the comments on files and fix accordingly

2023-10-11 10:50 UTC, MadhanSamiappan commented on assets/component-mega-menu.css
> +text-decoration: none;
for properties like font-family ,size you can use the base classess you created in styleguideline right?

2023-10-11 10:50 UTC, MadhanSamiappan commented on sections/header.liquid
> +      }
indents,
image picker info

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/header-drawer.liquid
> +                                 </div>                                   {% endcomment %}
remove commented out code

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/header-drawer.liquid
> +                                      class="menu-drawer__menu-item link link--text list-menu__item focus-inset kdfdk"
remove scrap class

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/header-drawer.liquid
> +
remove extra lines

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/header-drawer.liquid
> +                                              class="menu-drawer__menu-item link link--text list-menu__item focus-inset dkfldk{% if grandchildlink.current %} menu-drawer__menu-item--active{% endif %}
remove unwanted texts

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/header-mega-menu.liquid
> +                                      src="{{ block.settings.megamenu_image | image_url }}"
use image snippet instead of putting img tag directly

2023-10-11 10:50 UTC, MadhanSamiappan commented on snippets/icon-arrow.liquid
> +</svg> {% endcomment %}
remove commented code

2023-10-11 10:50 UTC, MadhanSamiappan commented on assets/component-menu-drawer.css
> +  background: #F6F6F7;
always create a base class for repeating props like bg color here

2023-10-11 16:44 UTC, NikhitaDesai commented on sections/header.liquid
> +      }
I changed this code

2023-10-12 05:42 UTC, MadhanSamiappan approved these changes
Code review - 4.89
not using base classes

2023-10-12 16:19 UTC, merged