Merge feature 191023 nd homepage
marmetodevelopers/mivi-website pull request #3
Opened 2023-10-19 05:13 UTC by NikhitaDesai

### Problem
Created  megha menu and  Banner section as per the figma.
Monday Card Link :( megha menu) : https://marmeto-force.monday.com/boards/5104690360/pulses/5303953694
Monday Card Link ( banner section):https://marmeto-force.monday.com/boards/5104690360/pulses/5324507187
Preview link:  https://mivi-website.myshopify.com/?preview_theme_id=161424736533
### Solution
Added the relatable code and CSS properties to match the given figma.
 ![image](https://github.com/marmetodevelopers/mivi-website/assets/145182249/ef933f0c-f911-45e7-b013-632afab4e113)
![image](https://github.com/marmetodevelopers/mivi-website/assets/145182249/2896bab0-0268-4ae6-9d84-de4af29581fb)
### Impacted Areas megha menu all pages and banner section only homepage.
<Explain other areas of the application that could be affected by this change.>
### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.
Please review this PR and provide feedback. Thank you!

2023-10-19 07:09 UTC, NikhitaDesai commented
@MadhanSamiappan  Updated the changes, review the code

2023-10-20 07:45 UTC, MadhanSamiappan requested changes

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/featured-collection.liquid
> +  {%- if section.settings.auto_rotate and 4 > 1 -%}
hardcoded 4 > 1 will always be false
pls fix this

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/featured-collection.liquid
> +  {%- if 4 > 1 -%}
same as above comment

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/featured-collection.liquid
> +{{ 'custome.css' | asset_url | stylesheet_tag }}
spelling

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/featured-collection.liquid
> +     {
indent

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/header.liquid
> -  "blocks": [
why did we remove the blocks?

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/image-banner.liquid
> +{{ 'custome.css' | asset_url | stylesheet_tag }}
instead of rendering custom css on every section, render it directly on theme liquid

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/image-banner.liquid
> +  {% for block in section.blocks %}
use block id whenever using it for settings based css

2023-10-20 07:45 UTC, MadhanSamiappan commented on sections/image-banner.liquid
> +           <h2 class="h1 test">{{ block.settings.heading }}</h2>
remove test class

2023-10-21 13:58 UTC, NikhitaDesai commented on sections/header.liquid
> -  "blocks": [
The content of the blocks will come from the menu only

2023-10-23 05:25 UTC, MadhanSamiappan requested changes

2023-10-23 05:25 UTC, MadhanSamiappan commented on assets/custom.css
> +button.slider-button.slider-button--next {
do not apply slider if slides are only 3

2023-10-23 05:25 UTC, MadhanSamiappan commented on assets/custom.css
fix indents

2023-10-23 05:25 UTC, MadhanSamiappan commented on assets/custom.css
> +    margin: 8px 0px;
do not use base classes for other css props

2023-10-23 05:25 UTC, MadhanSamiappan commented on assets/custom.css
> +  width: 95% !important;
do not use important

2023-12-12 05:56 UTC, closed without merging